### ISSUE TITLE
Parallel Monte Carlo Method on PI

### ISSUE THREAD

**Issue by shankerr** [cloudmesh/cloudmesh-mpi#8]
- [x] document also the parallel usecase (Gregor I assume this is done) Provide link, the previous one did not work so I deleted the link. See here: https://github.com/cloudmesh/cloudmesh-mpi/blob/main/doc/chapters/report-mpi.md#running-monte-carlo-on-multiple-hosts

https://github.com/cloudmesh/cloudmesh-mpi/blob/main/doc/chapters/report-mpi.md#running-monte-carlo-on-multiple-hosts

- [x] provide theory documentation with equation/image
- [x] provid implementation
- [x] include into document
- [x] figure out how to run on multiple hosts

**Comment by laszewsk** [comment]
what is progress ...?

**Comment by flealc** [comment]
Ran in multiple PIs and worked. Very slow since I was not able to get Numba in the PIs and had to use the regular version, but it works just fine despite taking a long time.
I was not sure if I should document the process, but then realized that running a script on multiple hosts is already detailed here https://github.com/cloudmesh/cloudmesh-mpi/blob/main/doc/chapters/report-mpi.md#running-mpi-on-multiple-computers

**Comment by laszewsk** [comment]
please put runtime into documenation so that others know how long it will take

**Comment by flealc** [comment]
Added a paragraph documenting execution on multiple hosts with PI cluster. Can be found right **before** the numba section here: https://github.com/cloudmesh/cloudmesh-mpi/blob/main/doc/chapters/report-mpi.md#numba

**Comment by flealc** [comment]
I added this blurb about the parallel use case. It is at the end of the section. (Not sure why the link will not work even for me)
I am copying it here:

"Additionally, we can run this program on multiple hosts. For instance, you can use a machinefile or rankfile to execute the program on a PI cluster. Be advised, however, that we do not use numba on RaspberryOS, hence the execution of the program can take a relatively long time. For a reference, running `mpiexec -n 7 --machinefile machinefile ... parallel_pi.py" on a PI cluster consisting of a manager PI4 and six PI3 workers took around 40 minutes."
 
That's all I did, since all the task said was "figure out how to run on multiple hosts." Would you like me to add a step-by-step documentation?
